name: Generate EPG

on:
  schedule:
    # Run the script every 3 days at midnight UTC
    - cron: "0 0 */3 * *"
  
  # This allows the workflow to be manually triggered
  workflow_dispatch:

jobs:
  generate-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run EPG generator script
        run: |
          python epg_generator.py

      - name: Commit and push generated EPG
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name [user.name] "Your Name"
          git add .
          git commit -m "Update EPG"
          git push
