name: Generate and Update EPG Files

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  generate_epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run EPG generation script
        run: |
          python generate_epg.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email adrian.lalor1@gmail.com
          git config --global user.name [user.name] "Brock92"
          git add Clubber_TV.xml Clubber_TV_dummy.xml.gz
          git commit -m "Daily EPG update"
          git push

