name: Update EPG

on:
  schedule:
    - cron: "0 0 */3 * *"  # Every 3 days at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is available for rebasing

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Generate EPG
        run: python generate_epg.py

      - name: Commit changes locally
        run: |
          git config --global user.email adrian.lalor1@gmail.com
          git config --global user.name [user.name] "Brock92"
          git add Clubber_tv.xml Clubber_tv.xml.gz
          git commit -m "Staging EPG updates" || echo "No changes to commit"

      - name: Pull latest changes and resolve conflicts
        run: |
          git fetch origin
          git merge --strategy-option=theirs origin/main || echo "Conflicts resolved using 'theirs' strategy"

      - name: Push final changes
        run: |
          git push || echo "No changes to push"
